// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleAnalysis.Domain.Models;

public partial class EventFrame
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    public Guid EventFrameTypeId { get; set; }

    [ForeignKey("EventFrameTypeId")]
    [InverseProperty("EventFrames")]
    public virtual EventFrameType EventFrameType { get; set; }

    [InverseProperty("EventFrame")]
    public virtual ICollection<EventFrameValue> EventFrameValues { get; set; } = new List<EventFrameValue>();

    [InverseProperty("ChildEventFrame")]
    public virtual ICollection<Link> LinkChildEventFrames { get; set; } = new List<Link>();

    [InverseProperty("ParentEventFrame")]
    public virtual ICollection<Link> LinkParentEventFrames { get; set; } = new List<Link>();
}