// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleAnalysis.Domain.Models;

public partial class EventFrameType
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("EventFrameType")]
    public virtual ICollection<EventFrameTypeValue> EventFrameTypeValues { get; set; } = new List<EventFrameTypeValue>();

    [InverseProperty("EventFrameType")]
    public virtual ICollection<EventFrame> EventFrames { get; set; } = new List<EventFrame>();

    [InverseProperty("ChildEventFrameType")]
    public virtual ICollection<Link> LinkChildEventFrameTypes { get; set; } = new List<Link>();

    [InverseProperty("ParentEventFrameType")]
    public virtual ICollection<Link> LinkParentEventFrameTypes { get; set; } = new List<Link>();
}