// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleAnalysis.Domain.Models;

public partial class EventFrameValue
{
    [Key]
    public Guid Id { get; set; }

    public Guid EventFrameId { get; set; }

    public Guid UserfieldId { get; set; }

    [StringLength(100)]
    public string ValueText { get; set; }

    public int? ValueInt { get; set; }

    public double? ValueFloat { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ValueDatetime { get; set; }

    [ForeignKey("EventFrameId")]
    [InverseProperty("EventFrameValues")]
    public virtual EventFrame EventFrame { get; set; }

    [ForeignKey("UserfieldId")]
    [InverseProperty("EventFrameValues")]
    public virtual EventFrameTypeValue Userfield { get; set; }
}