// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SampleAnalysis.Domain.Models;

public partial class EventFrameTypeValue
{
    [Key]
    public Guid Id { get; set; }

    public Guid EventFrameTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Type { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [ForeignKey("EventFrameTypeId")]
    [InverseProperty("EventFrameTypeValues")]
    public virtual EventFrameType EventFrameType { get; set; }

    [InverseProperty("Userfield")]
    public virtual ICollection<EventFrameValue> EventFrameValues { get; set; } = new List<EventFrameValue>();
}